---
- name: docker | install prereqs
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=600
  with_items:
    - apt-transport-https
    - ca-certificates
    - linux-image-extra-{{ ansible_kernel }}

- name: docker | apt signing key
  apt_key:
    keyserver: 'pool.sks-keyservers.net'
    id: '58118E89F3A912897C070ADBF76221572C52609D'
  notify: 'docker-apt-get-update'

- name: docker | apt repo
  apt_repository:
    repo: 'deb https://apt.dockerproject.org/repo {{ansible_distribution|lower}}-{{ ansible_distribution_release }} main'
    state: 'present'
  notify: 'docker-apt-get-update'

- meta: flush_handlers

- name: docker | remove legacy package
  apt: name=lxc-docker state=absent

- name: docker | install
  apt: name=docker-engine state=latest

- name: docker | start service
  service: name=docker state=started enabled=yes

#- name: docker | add user to docker group
#  user: name={{ ansible_user_id }} groups=docker append=yes 

- name: Add user(s) to docker group
  user: 
      name={{ item }} 
      group=docker 
      state=present
  with_items: "{{ docker_users }}"
  when: docker_users is defined

#- name: nvidia-docker | download deb
#  get_url: url="https://github.com/NVIDIA/nvidia-docker/releases/download/v1.0.0-rc.3/nvidia-docker_1.0.0.rc.3-1_amd64.deb" dest="/tmp/nvidia-docker.deb"

#- name: nvidia-docker | install deb
#  apt: deb=/tmp/nvidia-docker.deb
